### ISSUE TITLE
Ensure search is enabled everywhere, or nowhere

### ISSUE THREAD

**Issue by gburd** [basho/riaknostic#11]
In Riak 0.14.x -> 1.0.x `riak-admin leave` and other operations can hang if the ring isn't fully configured for search (if say one of 5 nodes didn't enable search in app.config).  Check for this around the ring and output an error message if search is enabled on any one, but not all, nodes in the cluster.

**Comment by seancribbs** [comment]
This could be generalized to "differences between active configurations beyond the listeners/etc".

**Comment by ghost** [comment]
This particular issue now has a check enabled for it.
