### ISSUE TITLE
Create documentation/splash site

### ISSUE THREAD

**Issue by seancribbs** [basho/riaknostic#13]
We need an awesome documentation site that includes:
- Splash page with some nice overview, descriptions, and a cool logo (logo discussed briefly with @jgnewman)
- Hosted on Github Pages for ease of update
- CNAME to riaknostic.basho.com
- Generated edoc included so people can understand how to use/extend the source (with a non-ugly stylesheet)

**Comment by jgnewman** [comment]
Yay!  I love me some cool logos!

**Comment by seancribbs** [comment]
@jgnewman The more doctor-like, the better! :)
