### ISSUE TITLE
Add machine-readable output format

### ISSUE THREAD

**Issue by seancribbs** [basho/riaknostic#14]
Suggested by @justinsheehy, Riaknostic should be able to dump the report in a machine-readable format. The format of this file could be Erlang terms (one would extract them using `file:consult/1`) and have a top-level structure like `{riaknostic_report, Vsn, Messages}`, where `Vsn` is a version number that can be changed when the internal structure changes and `Messages` would be messages output by the diagnostic modules.

The advantage of this format is that you could later manipulate the data with other programs or aggregate results across a large cluster.

**Comment by evanmcc** [comment]
A couple of questions: 
- do we want this dumped to a file, or to standard out?
- Is there a transform that we need to apply to the messages to make them easier to parse?  Right now they look something like this:

{notice,riaknostic_check_disk,{atime,
                                             [47,85,115,101,114,115,47,101,118,97,110,47,115,114,99,
                                              47,114,105,97,107,47,100,101,118,47,100,101,118,49,47,
                                              100,97,116,97,47,98,105,116,99,97,115,107]}}

I have a really basic pass at this done, but I am not sure precisely how we want it to come out.

**Comment by bsparrow435** [comment]
Closing this for now. Export functionality is implemented with `riak-debug` and riaknostic reports are now also written to console.log making it easy to aggregate with any log analysis tool.
