### ISSUE TITLE
Provide deb/rpm packages

### ISSUE THREAD

**Issue by ghost** [basho/riaknostic#27]
Rather than downloading and untar-ing the package, having a deb/rpm package would make it easier to install.

**Comment by evanmcc** [comment]
@jaredmorrow suggests this:  https://github.com/jordansissel/fpm/

Another thing that we could do to make it easer to install would be to put some logic into riak-admin to optionally pull it down and unpack it (via the tarball).

I think that it might be useful to put in some customer outreach work to try and figure out why people aren't picking it up.

**Comment by derpston** [comment]
Just untarring something means that the system's packaging utilities won't know it is there, won't be able to upgrade/uninstall it, and the code won't be signed. I don't think this would be solved by giving riak-admin the ability to download code, install it, and execute it.

Riaknostic ought to have signed deb/rpm packages, it's the only way to distribute code that will be trusted and accepted by most sysadmins.

riak-admin could recommend the apt/yum command to run to install the optional packages, but it shouldn't execute it.

**Comment by evanmcc** [comment]
_nod_

**Comment by jaredmorrow** [comment]
The current thought is to just include riaknostic into the Riak package itself and avoid this whole mess of the user installing it in whatever fashion.

**Comment by derpston** [comment]
That sounds good. Less work for everyone, probably!

**Comment by fprimex** [comment]
Just house keeping: Riaknostic is shipped with Riak now. Closing.
