### ISSUE TITLE
N Value - Preflist Message is Vague

### ISSUE THREAD

**Issue by ghost** [basho/riaknostic#28]
The message we generate, "The following preflists do not satisfy the n_val" needs to be more verbose, and offer advice on how to remedy the situation.

**Comment by evanmcc** [comment]
@bsparrow435 @jmshoffs0812 I have to admit that I am not 100% certain what this means or how to fix it.  I am assuming that it's something to do with data loss, maybe after you've lost the store on a node?

**Comment by evanmcc** [comment]
From @seancribbs on HC: 

Evan: can anyone explain the preflists don't satisfy n_val check to me (from riak_core_ring_util.erl)?
Sean Cribbs: evan: that means "these preflists have more than one replica on the same node"
Evan: mostly a cluster too small issue?
Sean Cribbs: yes
Sean Cribbs: and in certain combinations of ring size and node count, e.g. 256p/5n was a problematic one in the past

This information makes it easy to update the warning, but I am not totally sure how to automatically give good recommendations (other than the good but often impossible "add many more nodes, wait for it to rebalance").
