### ISSUE TITLE
Add inode/du tests

### ISSUE THREAD

**Issue by ghost** [basho/riaknostic#31]

**Comment by evanmcc** [comment]
@bsparrow435, did you ever finish up this patch?  If you're part of the way there, I can finish/test it for you, if you point me to the branch.

**Comment by fprimex** [comment]
This falls pretty squarely in the domain of riak-debug now, so I think we can close this out. Riaknostic should be doing more "from the POV of Riak, what's wrong" type of checking, like "can we make a file? if not, error." At any rate, adding `df -i` to riak-debug for info gathering.

**Comment by bsparrow435** [comment]
Thanks Brent!
