### ISSUE TITLE
Check Logs

### ISSUE THREAD

**Issue by ghost** [basho/riaknostic#34]
Riaknostic should have the ability to check logs for known potential errors, such as emfile or busy_dist_port

**Comment by evanmcc** [comment]
Is there a good list of things to look for in the docs somewhere?

**Comment by alexmoore** [comment]
We are putting this in the riak_debug script as part of an "analyze" flag/option.  
basho/riak@7f2b3216401760428160c347b0ea68f66bc5fb2c
