### ISSUE TITLE
Export functionality

### ISSUE THREAD

**Issue by bsparrow435** [basho/riaknostic#35]
Riaknostic should have an export argument that gathers useful information from riak-admin commands and logs and bundles them up. This would be useful in support situations so we could easily have customers send us the output of this command.

Example: riak-admin diag export <filename>

**Comment by seancribbs** [comment]
See also #14

**Comment by evanmcc** [comment]
@bsparrow435 if you could generate a list of the commands here, I'll get started on this one.

**Comment by bsparrow435** [comment]
@evanmcc looking at the riak-admin commands now, will let you know which ones I feel are the most useful for this.

**Comment by evanmcc** [comment]
longer term: folding in a lot of these stats (and their linux/bsd equivalents), would be really nice:  http://dtrace.org/blogs/brendan/2012/03/01/the-use-method-solaris-performance-checklist/

**Comment by bsparrow435** [comment]
Closing this and removing export functionality. This is now implemented by `riak-debug`
