### ISSUE TITLE
riaknostic should check the scheduler on linux systems

### ISSUE THREAD

**Issue by evanmcc** [basho/riaknostic#42]
it should be either noop or deadline.

**Comment by evanmcc** [comment]
This is actually harder than I thought it was (and now I see why issue #46 is likely the way that it is).  In order to check this, you have to ascertain which drive your riak datastore lives on, then check the scheduler for that one.

**Comment by fprimex** [comment]
This is probably done more easily with the new riak-debug script. I am gathering this info there, so I recommend that we close this issue against Riaknostic.
