### ISSUE TITLE
riaknostic should check for monitor leaks [JIRA: TOOLS-403]

### ISSUE THREAD

**Issue by evanmcc** [basho/riaknostic#44]
Monitors aren't reaped during 2i, can leak badly if heavily used.  Should check for them.

monitor leak detection from console:
https://gist.github.com/79d12e79592c62ae0050

**Comment by bsparrow435** [comment]
moved to 2.1

**Comment by jonmeredith** [comment]
This may be useful for detection https://github.com/basho/riak_kv/pull/916

**Comment by bsparrow435** [comment]
Fixed.
