### ISSUE TITLE
riaknostic should make conservative performance suggestions

### ISSUE THREAD

**Issue by evanmcc** [basho/riaknostic#45]
checking for +s N:N line in vm.args on systems with many many cores
checking for TCP tuning parameters 
checking for sysclt tuning parameters 

Anything else?

**Comment by fprimex** [comment]
check for number of erlang ports and processes in vm.args

**Comment by evanmcc** [comment]
+S N:N where N = (+ cores (/ ring_creation_size num-nodes)), round up a little

+zdbbl 16384 just generally, I imagine it won't be harmful on many machines

**Comment by evanmcc** [comment]
https://github.com/basho/DevOps/wiki/tunes-n-stuff

**Comment by bsparrow435** [comment]
Now implemented by riak_kv_env.erl
