### ISSUE TITLE
Add Bitcask data file checking functionality [JIRA: TOOLS-398]

### ISSUE THREAD

**Issue by fprimex** [basho/riaknostic#47]
Reminder to add Bitcask data file checking functionality. Scripts that accomplish this task have already been written and should be rolled in.

**Comment by evanmcc** [comment]
@fprimex could you add some links or references to those scripts?

**Comment by bsparrow435** [comment]
moved to 2.1

**Comment by bsparrow435** [comment]
We have improve logging which handles this case more gracefully. Closing.
