### ISSUE TITLE
Add check for new 2i sext encoding if version >= 1.3.1

### ISSUE THREAD

**Issue by fprimex** [basho/riaknostic#57]
Riak 1.3.1 introduces a new integer encoding for secondary indexes. The indexes on an upgraded cluster must be upgraded by issuing a command (see the release notes for 1.3.1). We should check that Riak >= 1.3.1 is using the new encoding. Perhaps we should also generally check that Riak is using the right encoding for its version, since downgrades are possible.

@jrwest says

"""
Something like [1] could be added to get vnode status, then check for {fixed_indexes, true} in returned proplists of each vnode?

[1] https://github.com/basho/riaknostic/blob/master/src/riaknostic_node.erl#L200
"""

**Comment by jrwest** [comment]
I added a status function in https://github.com/basho/riak_kv/pull/560 that is meant to be used for this purpose. Riaknostic should be able to call it and print something sensible w/ the return values. @bsparrow435 would this be something easy for you to add quickly?

**Comment by bsparrow435** [comment]
With 1.2 no longer supported, this work will probably not happen.
