### ISSUE TITLE
Info Dump

### ISSUE THREAD

**Issue by bsparrow435** [basho/riaknostic#59]
Similar to a cluster-info, riaknostic should work with riak-debug to provide a nice info dump from a customers cluster. How this is implemented is still up in the air but this issue will track work and ideas.

**Comment by fprimex** [comment]
Here is what all riak-debug is dumping, command-wise. This would get us started. This info, plus a dump of the ring, all in one data structure, provided by one command, especially if it could be JSON, would be AMAZING.

```
riak ping # probably unneeded since riaknostic is talking to the node for info
riak version # redundant since this is in status
riak-admin member-status
riak-admin ring-status
riak-admin status
riak-admin transfers
riak-admin diag # ignore this; don't run checks when producing this info dump
riak-repl status

# "extra" commands, considered heavy
# It'd be nice if riaknostic could do everything in a very light way, to provide some 'safety'
riak-admin vnode-status
```

**Comment by bsparrow435** [comment]
`riak-debug` currently calls riaknostic. Improvements to riaknostic should make this more useful
