### ISSUE TITLE
Riaknostic fails to run on Centos 5

### ISSUE THREAD

**Issue by jaredmorrow** [basho/riaknostic#62]
I was just trying to use riaknostic on my centos 5.7 builder and ran into a problem executing the script.  Here is my test run (with attempts to add sysctl to my path)

```
[buildbot@build-centos-5-64 packages]$ sudo riak-admin diag
escript: exception error: bad argument
  in function  list_to_integer/1
     called as list_to_integer("sh: line 0: exec: sysctl: not found")
  in call from riaknostic_check_sysctl:check_params/2 (src/riaknostic_check_sysctl.erl, line 80)
  in call from riaknostic_check:check/1 (src/riaknostic_check.erl, line 74)
  in call from riaknostic:'-run/1-fun-1-'/2 (src/riaknostic.erl, line 116)
  in call from lists:foldl/3 (lists.erl, line 1197)
  in call from riaknostic:run/1 (src/riaknostic.erl, line 115)
[buildbot@build-centos-5-64 packages]$ riak-admin diag
escript: exception error: bad argument
  in function  list_to_integer/1
     called as list_to_integer("sh: line 0: exec: sysctl: not found")
  in call from riaknostic_check_sysctl:check_params/2 (src/riaknostic_check_sysctl.erl, line 80)
  in call from riaknostic_check:check/1 (src/riaknostic_check.erl, line 74)
  in call from riaknostic:'-run/1-fun-1-'/2 (src/riaknostic.erl, line 116)
  in call from lists:foldl/3 (lists.erl, line 1197)
  in call from riaknostic:run/1 (src/riaknostic.erl, line 115)
[buildbot@build-centos-5-64 packages]$ which sysctl
/sbin/sysctl
[buildbot@build-centos-5-64 packages]$ sudo su -
[root@build-centos-5-64 ~]# which riak
/usr/bin/riak
[root@build-centos-5-64 ~]# riak-admin diag
escript: exception error: bad argument
  in function  list_to_integer/1
     called as list_to_integer("sh: line 0: exec: sysctl: not found")
  in call from riaknostic_check_sysctl:check_params/2 (src/riaknostic_check_sysctl.erl, line 80)
  in call from riaknostic_check:check/1 (src/riaknostic_check.erl, line 74)
  in call from riaknostic:'-run/1-fun-1-'/2 (src/riaknostic.erl, line 116)
  in call from lists:foldl/3 (lists.erl, line 1197)
  in call from riaknostic:run/1 (src/riaknostic.erl, line 115)
[root@build-centos-5-64 ~]# which sysctl
/sbin/sysctl
```

**Comment by jmthackett** [comment]
Similar here, this time on a fresh install of debian squeeze:

<pre>
riak-1:~# riak-admin diag
RPC to 'riak@127.0.0.1' failed: {'EXIT',
                                 {badarg,
                                  [{erlang,list_to_integer,
                                    ["sh: line 0: exec: sysctl: not found"],
                                    []},
                                   {riaknostic_check_sysctl,check_params,2,
                                    [{file,"src/riaknostic_check_sysctl.erl"},
                                     {line,80}]},
                                   {riaknostic_check,check,1,
                                    [{file,"src/riaknostic_check.erl"},
                                     {line,74}]},
                                   {riaknostic,'-run/1-fun-1-',2,
                                    [{file,"src/riaknostic.erl"},{line,106}]},
                                   {lists,foldl,3,
                                    [{file,"lists.erl"},{line,1197}]},
                                   {riaknostic,run,1,
                                    [{file,"src/riaknostic.erl"},{line,105}]},
                                   {rpc,'-handle_call_call/6-fun-0-',5,
                                    [{file,"rpc.erl"},{line,203}]}]}}
riak-1:~# which sysctl
/sbin/sysctl
</pre>

**Comment by randysecrist** [comment]
also observed on debian wheezy

**Comment by fredyouhanaie** [comment]
I have just started trying out riak, and noticed the same errors. What I learned is that it is not the riak-admin that calls sysctl, but the riak daemon.
You may want to check if /sbin was in $PATH when you started riak.
For example, after building from source, this worked for me:

```
$ cd rel/riak
$ PATH=$PATH:/sbin
$ bin/riak start
$ bin/riak-admin diag
```

**Comment by zowers** [comment]
the problem is that user 'riak' does not have '/sbin' in it's PATH

**Comment by zowers** [comment]
`sudo ln -s /sbin/sysctl /bin/`
did the trick

**Comment by bsparrow435** [comment]
Thanks all for the comments and suggestions on this issue. As @zowers pointed out this has to do with `sysctl` not being in PATH. However, checks on erlang os ENV's and sysctl tunings have been moved to riak_kv_check.erl. I am in the process of removing riaknostic_check_sysctl and will note the PR when it is complete.
