### ISSUE TITLE
undef in riaknostic 2.1.5 [JIRA: TOOLS-476]

### ISSUE THREAD

**Issue by kpy3** [basho/riaknostic#94]
It seems riaknostic still relies on lager 2.2.x not 3.x:
```
se@qring1:~$ sudo riak-admin diag memory_use
RPC to 'xxxxxxx@xxxxxxxxxxx' failed: {'EXIT',
                                                 {undef,
                                                  [{lager,get_loglevels,[],[]},
                                                   {riaknostic,run,1,
                                                    [{file,
                                                      "/opt/build/_build/default/lib/riaknostic/src/riaknostic.erl"},
                                                     {line,118}]},
                                                   {rpc,
                                                    '-handle_call_call/6-fun-0-',
                                                    5,
                                                    [{file,"rpc.erl"},
                                                     {line,205}]}]}}
```

**Comment by toteva** [comment]
Same issue with

riak-admin diag
RPC to 'riak@XXXXXXXXXXXXX' failed: {'EXIT',
                                      {undef,
                                       [{lager,get_loglevels,[],[]},
                                        {riaknostic,run,1,
                                         [{file,"src/riaknostic.erl"},
                                          {line,121}]},
                                        {rpc,'-handle_call_call/6-fun-0-',5,
                                         [{file,"rpc.erl"},{line,205}]}]}}

**Comment by bsparrow435** [comment]
Fixed thank you very much for the report and PR.
